//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DivingSuit.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class DivingSuit extends Item implements Item {
	private boolean isOn;
	public boolean PutOn(Player p) {
	}
	
	public boolean Swim(Player p) {
	}
	
	public void Drop(Player p) {
	}
}
