//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Player {
	protected int hp;
	protected int numberOfAction;
	protected int maxHp;
	protected boolean win;
	private Field field;
	private Game players;
	private Item items;
	private Game currentPlayer;
	public void UseAbility() {
	}
	
	public void Move(Field f) {
	}
	
	public void IncreaseHp() {
	}
	
	public void DecreaseHp() {
	}
	
	public void AddItem(Inventory i) {
	}
	
	public void RemoveItem(Inventory i) {
	}
	
	public void StartTurn(int numOfAction) {
	}
	
	public void DigPlayer(int layers) {
	}
	
	public void SwimPlayer() {
	}
	
	public void PullPlayer() {
	}
}
