//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableField.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class UnstableField extends Field {
}
