//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Eskimo extends Player {
	/**
	 * 
	 * @param field	Ahova az eszkimót ledobjuk a pályán. 
	 */
	public Eskimo(Field field) {
		super(4, field);
	}
	
	public void UseAbility() {
	}
}
