//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Eskimo.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Eskimo extends Player {
	public void UseAbility() {
	}
}
