//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Field {
	protected int capacity;
	protected int snowLayer;
	protected boolean hasIglu;
	protected boolean visibleCapacity;
	protected int numOfPlayers;
	protected Field neighbourFields;
	private Board fields;
	private Player players;
	
	public Field() {
		
	}
	
	public void Init(Field neighbour) {
	}
	
	public boolean IsFall() {
	}
	
	public void Fall() {
	}
	
	public void CanBuildIglu() {
	}
	
	public void AddItem(Inventory item) {
	}
	
	public void RemoveItem(Player p) {
	}
	
	public void DigItems(int layers) {
	}
	
	public boolean IsFull() {
	}
	
	public void AddPlayer(Player p) {
	}
	
	public void RemovePlayer(Player p) {
	}
}
