package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flare.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Flare extends FlareGun implements Inventory {
	
	public Flare(int layer, boolean visible,int tab) {
		super(layer,visible, tab+1);
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.println("A Flare osztaly konstruktora hivodott meg.");
		}
}
