//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FlareGun.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class FlareGun implements Inventory {
	protected int layer;
	protected boolean visible;
	protected FlareGun components;
	public boolean Shoot(Player p) {
	}
	
	public boolean Eat(Player p) {
	}
	
	public boolean Dig(Player p) {
	}
	
	public boolean Pull(Player p) {
	}
	
	public boolean PutOn(Player p) {
	}
	
	public boolean Swim(Player p) {
	}
	
	public void Drop(Player p) {
	}
	
	public void PickUp(Player p) {
	}
	
	public void DecreaseLayer(int i) {
	}
}
