package classes;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FlareGun.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class FlareGun implements Inventory {
	protected int layer;
	protected boolean visible;
	protected ArrayList<FlareGun> components;
	public boolean Shoot(Player p, int tab) {
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.print("A FlareGun osztaly Shoot() fuggvenye hivodott meg");
		if (p.GetNumOfAction(tab + 1) <= 0)
			return false;
		if (!(components.contains(new Gun()) && components.contains(new Flare()) && components.contains(new Cartridge()))) {
			return false;
		}
		p.SetWin(true);
		return true;
		
	}
	
	public boolean Eat(Player p) {
		return false;
	}
	
	public boolean Dig(Player p) {
		return false;
	}
	
	public boolean PutOn(Player p) {
		return false;
	}
	
	public boolean Swim(Player p) {
		return false;
	}
	
	public void Drop(Player p) {
	}
	
	public void PickUp(Player p) {
	}
	
	public void DecreaseLayer(int i, int tab) {
		for(int j=0; j<tab; j++)
			System.out.print("\t");
		System.out.print("A Item osztaly DecreaseLayer() fuggvenye hivodott meg");
		layer -= i;
	}

	public boolean Pull(Player p, Field to) {
		return false;
	}


	public void SetLayer(int num) {
		this.layer=num;
		System.out.printf("Az Item oszt�ly SetLayer(num:int):void h�v�dott meg \n");
	}

	public int GetLayer(int tab) {
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.print("A Item osztaly GetLayer() fuggvenye hivodott meg");
		return layer;
	}

	public void SetVisible(boolean b, int tab) {
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.print("Az Item osztaly SetVisible() fuggvenye hivodott meg");
		visible = b;
		
	}
}
