package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flare.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//

/**
 * 
 * Kulonleges targy, mert a jatek megnyeresehez elengedhetetlen. 
 * Barmely tipusu jatekos felveheti amely egy egyseg munkat vesz igenybe. A nyereshez a masik ket 
 * fontos alkatr�sszel kell osszeszerelni, ami szinten egy munka.
 *
 */


public class Flare extends FlareGun implements Inventory {
	/**
	 * 
	 * @param layer mennyi reteg ho van a targy felett
	 * @param visible ez akkor igaz ha lathato a targy(nincs rajta ho)
	 * @param tab indentalas
	 */
	public Flare(int layer, boolean visible,int tab) {
		super(layer,visible, tab+1);
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.println("A Flare osztaly konstruktora hivodott meg.");
		}
}
