//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flare.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Flare extends FlareGun implements Item {
}
