package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Food extends Item {
	
	public Food(int layer,boolean visible) {
		super(layer, visible);
	}
	
	public boolean Eat(Player p, int tab) {
		if (p.GetNumOfAction(tab + 1) <= 0)
			return false;
		if (p.GetHP() == p.GetMaxHP()) {
			return false;
		}
		p.SetNumOfAction(p.GetNumOfAction(tab + 1) - 1, tab + 1);
		p.RemoveItem(this, tab + 1);
		return true;
	}
}
