package classes;

import java.util.ArrayList;


//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//
/**
 * Az osztály egy játék felépítéséért és lebonyolításáért felel. 
 * Statikusak a függvényei és a paraméterei is, így tettük lehetõvé, hogy ha a játék folyamán a
 * Game osztályt használjuk, ne kelljen példányosítani, a változtatások az elején létrehozott
 * Game-ben történjenek
 *
 */
public class Game {
	private static Player currentPlayer;
	private static ArrayList<Player> players;
	private static Board board;
	
	public static Player GetCurrentPlayer(int tab) {
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.printf("A Game osztály GetCurrentPlayer():Player hívódott meg \n");
		return currentPlayer;
	}
	public static void SetCurrentPlayer(Player player,int tab) {
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.printf("A Game osztály SetCurrentPlayer():Player hívódott meg \n");
		currentPlayer=player;
	}
	/*public static void Init(ArrayList<Player> players, Board board) {
	}
	
	public static void StartGame() {
	}
	
	public static boolean SomeoneDied() {
	}
	
	public static void LoseGame() {
	}
	
	public static boolean Win() {
	}*/ //Inicializáláshoz kellenek
}
