//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Game {
	public void Init(Player [1..*] players, Board board) {
	}
	
	public void StartGame() {
	}
	
	public boolean SomeoneDied() {
	}
	
	public void LoseGame() {
	}
	
	public boolean Win() {
	}
}
