package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gun.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Gun extends FlareGun implements Inventory {
}
