package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gun.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Gun extends FlareGun implements Inventory {
	
	public Gun(int layer, boolean visible,int tab) {
	super(layer,visible, tab+1);
	for(int i=0; i<tab; i++)
		System.out.print("\t");
	System.out.println("A Gun osztaly konstruktora hivodott meg.");
	}
}
