//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hole.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Hole extends Field {
	public boolean IsFall() {
	}
	
	public void CanBuildIglu() {
	}
	
	public void AddItem(Inventory item) {
	}
	
	public void DigItems(int layers) {
	}
	
	public boolean IsFull() {
	}
	
	public void RemoveItem(Inventory item) {
	}
}
