package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hole.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Hole extends Field {
	
	public Hole(int tab) {
		super(0, 0, tab);
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.println("A Hole osztaly konstruktora hivodott meg.");
	}
	
	public boolean IsFall() {
	}
	
	public void CanBuildIglu() {
	}
	
	public void AddItem(Inventory item) {
	}
	
	public void DigItems(int layers) {
	}
	
	public boolean IsFull() {
	}
	
	public void RemoveItem(Inventory item) {
	}
}
