package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Inventory.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public interface Inventory {
	public boolean Eat(Player p);
	
	public boolean Dig(Player p);
	
	public boolean Pull(Player p, Field to);
	
	public boolean PutOn(Player p);
	
	public boolean Shoot(Player p);
	
	public boolean Swim(Player p);
	
	public void Drop(Player p);
	
	public void DecreaseLayer(int i, int tab);
	
	public void PickUp(Player p);
	
	public int GetLayer(int tab);
	
	public void SetLayer(int num);
	
	public void SetVisible(boolean b, int tab);
}
