//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rope.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Rope extends Item implements Item {
	public boolean Pull(Player p) {
	}
}
