//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shovel.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Shovel extends Item implements Item {
	public boolean Dig(PLayer p) {
	}
}
