package classes;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shovel.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class Shovel extends Item {
	
	public Shovel(int layer,boolean visible) {
		super(layer, visible);
	}
	
	public boolean Dig(Player p) {
		if (p.GetNumOfAction() <= 0)
			return false;
		p.SetNumOfAction(p.GetNumOfAction() - 1);
		p.DigPlayer(2);
		return true;
	}
}
