//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StableField.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//




public class StableField extends Field {
	private StableField neighborFields;
	public boolean IsFall() {
	}
	
	public void Fall() {
	}
}
