package classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableField.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//



/**
 * Egy “instabil” mezõt reprezentál, tehát néhány játékost bír el az adott mezõ, de nem
 * az összeset.
 */
public class UnstableField extends Field {
	
	public UnstableField(int capacity, int snowLayer, int tab) {
		super(capacity, snowLayer, tab);
		for(int i=0; i<tab; i++)
			System.out.print("\t");
		System.out.println("Az UnstableField osztaly konstruktora hivodott meg.");
	}
}
