package classes;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UnstableField.java
//  @ Date : 3/27/2020
//  @ Author : 
//
//



/**
 * Egy �instabil� mez�t reprezent�l, teh�t n�h�ny j�t�kost b�r el az adott mez�, de nem
 * az �sszeset.
 */
public class UnstableField extends Field {
	
	/**
	 * Konstruktor
	 * @param capacity
	 * @param snowLayer
	 * @param tab
	 */
	public UnstableField(int capacity, int snowLayer) {
		super(capacity, snowLayer);
	}
	
	public boolean isFall(){
		if(numOfPlayers >= capacity){
			return true;
		}
		else{
			return false;
		}
	}
}
